defaults:
    # General settings
    - generic_longitudinal
module:
    _target_: train_longitudinal.LongitudinalTrainingModule
    num_inter_by_epoch: 7
max_steps: 15000
accumulate_grad_batches: 4
sim_loss: "mi"
lambda_reg: 0.01
lambda_sim: 1.0
learning_rate: 0.001
save_dir: 'longitudinal/mlp'
batch_size: 1
checkpoint: ""
time_mode: "mlp"
load: ""