_target_: registration_svf.registration.RegistrationModule
int_steps: 9
model:
  _target_: registration_svf.modules.unet.DyNUnet
  dropout: 0.1
  in_channels: 2
  out_channels: 3
  kernel_size: [[3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
  strides: [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
