_target_: modules.registration.RegistrationModule
int_steps: 9
model:
  _target_: monai.networks.nets.DynUNet
  dropout: 0.1
  spatial_dims: 3
  in_channels: 2
  out_channels: 6
  kernel_size: [[3, 3, 3], [3, 3, 3],[3, 3, 3], [3, 3, 3], [3, 3, 3]]
  strides: [[1, 1, 1], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
  upsample_kernel_size: [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]

