# network configs
loss_type: 'mse'
down_channels: [32, 64, 128, 128, 256]
up_channels: [256, 128, 128, 64, 32]
time_emb_dim: 64
decoder_only: false

# training configs
batch_size: 1
res_levels: 8
ss_lr: 1e-4
ss_epochs: 500
ss_eval_interval: 1
checkpoints_path: 'checkpoints/furet.pt'
logdir: 'logs/furet.log'

# loss factors
image_loss_coeff: 1.
ss_loss_coeff: 1e3

# evaluation configs
down_factor: 2
save_evals: true
save_evals_path: 'evals/furet'
eval_logdir: 'logs/furet.log'
