defaults:
  - data: macaque
  - svf_model: dyn_unet_dual
  - train_pair: macaque

hydra:
  job:
    name: pairwise
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
    subdir: version_${hydra.job.num}

