max_steps: 15000
accumulate_grad_batches: 4
lambda_sim: 0
lambda_seg: 1.0
lambda_reg: 100
learning_rate: 0.001
tensor_cores: false
batch_size: 1
checkpoint: ""
penalize: "v"
save_dir: 'registration'

